---
title: "Research & Publications"
format:
  html:
    toc: false
---

------------------------------------------------------------------------

***Academic Publication***

### Can Two Wrongs Make a Right? The Buffering Effect of Retaliation on Subordinate Well-Being Following Abusive Supervision

Why do mistreated employees choose to retaliate against abusive supervisors? Can retaliation have unexpected positive impacts on their well-being and perceptions of fairness in the long run?

-   [Press Coverage: BBC Worklife](https://www.bbc.com/worklife/article/20211214-can-you-ever-get-over-a-lingering-grudge)

Liang, L. H., **Coulombe, C.,** Brown, D. J., Lian, H., Hanig, S., Ferris, D. L., & Keeping, L. M. (2022). Can two wrongs make a right? The buffering effect of retaliation on subordinate well-being following abusive supervision. J*ournal of Occupational Health Psychology, 27*(1), 37–52.

::: {.callout-caution collapse="true" appearance="minimal" icon="false"}
## What's the Gist?

-   Retaliation may reduce the negative impact of abusive supervision on employee well-being.
-   Retaliation may weaken the connection between experiencing abuse from a supervisor and feelings of injustice.
-   Direct retaliation against supervisors may be more effective in restoring justice perceptions than indirect methods.
-   Retaliation's positive effects persist over time, even after controlling for baseline well-being.
-   Alternative methods like expressive writing should also be considered as less destructive responses.
:::

::: {.callout-note collapse="true" appearance="minimal" icon="false"}
## Read More

**Overview**

An unfortunate reality in many workplaces today is the existence of supervisors whose leadership style borders on the abusive. This not only creates a toxic work environment but also understandably takes a toll on the well-being of subordinates, fostering feelings of injustice and erosion of morale. When employees are confronted with an abusive supervisor, a common coping mechanism is to take the path of retaliation. Rather than silently enduring mistreatment, many choose to respond by dishing out what they get, aiming to redress the balance of justice and even the score.

**Study 1**

In our first study, we recruited over 200 full-time employees who were currently working for an abusive supervisor. We surveyed them at three time points. First, we asked them how often their supervisors showed abusive behaviors (e.g., ridiculing them, putting them down in front of others, saying negative things about them behind their backs) and how often they retaliated (e.g., acting rudely towards the supervisor, making fun of them, gossipping about them). Around one week later, we measured the extent to which they felt a sense of justice in their relationship with their supervisor and how emotionally drained they felt by their work. Another week later, we assessed their level of job satisfaction, commitment to their organization, how much tension and anxiety they felt as a result of their work, and how many somatic symptoms they felt (e.g., headaches, stomach problems, trouble sleeping). 

​Our analyses yielded three key findings:​

​**1. The more employees retaliate, the less acts of abusive supervision are connected to feelings of injustice.** In the presence of an abusive supervisor, employees are likely to experience lower perceptions of justice in their relationship with that supervisor. However, the degree to which this connection is felt can be influenced by employee retaliation. Specifically, the more employees retaliate, the weaker this connection becomes (i.e., they don't tend to feel as much injustice in their relationship with their abusive supervisor). This may be because employees perceive that by retaliating, they've effectively "gotten back" at their supervisor and restored the imbalance of justice.

**2. The more employees retaliate, the less acts of abusive supervision tend to harm their well-being at work, given their restored sense of justice.** Employees of abusive supervisors tend to report lower job satisfaction more emotional exhaustion. Part of why these negative outcomes happen can be explained by the higher sense of injustice they tend to experience at work. Feelings of injustice are a strong stressor at work, especially since humans are motivated to believe that they live in a world where people get what they deserve and deserve what they get. When a person experiences abusive supervision, retaliation may help protect their well-being by restoring perceptions of interpersonal justice.

**3. The type of retaliation matters.** We explored the effects of different ways of retaliating. Directly acting against a supervisor (e.g., acting rudely towards them) was found to be more effective in restoring a sense of justice compared to indirect methods (e.g., gossiping, taking it out on the organization). 

**Study 2**

To better understand this phenomenon, we ran a second study that extended Study 1 in three ways:

1.  **Controlling for baseline well-being:** A person's past well-being can influence their current state of well-being. In Study 2, we controlled for their baseline well-being to be able to more accurately see the impact of the variables we were looking at.

2.  **Long-term impact of retaliation:** Although retaliation may feel good in the moment, it's possible that it could carry long-term repercussions (e.g., if it escalates conflict or results in punishment or counter-retaliation). In Study 2, we extended the study period to 4 months to get a better sense of these long-term implications. 

3.  **Alternative explanations:**To add to our understanding of why retaliation seems to mitigate the negative effects of abusive supervision on well-being, we considered an additional explanation beyond restored justice perceptions. Specifically, we looked at whether those who retaliate are less likely to see themselves as victims. 

In Study 2, we replicated the process from Study 1, but with a new sample of 250 full-time employees. Our initial survey at Time 1 involved measures of abusive supervision, retaliation, and indicators of well-being i.e., job satisfaction, affective commitment, emotional exhaustion, tension, somatic complaints) to serve as a baseline measure. Our second survey was around 4 months later. In this survey, we measured perceptions of interpersonal justice and of victim identity. Our last survey was around one week after the second. We assessed indicators of subordinate well-being again, to be able to look at the difference since the Time 1 survey. 

Our analyses yielded three key findings:

**1. Replication of Study 1 results.** We were able to replicate the key findings from Study 1, reinforcing our confidence in the patterns we observed.

**2. Victim identity didn't emerge as a plausible explanation.** Our analyses showed that victim identity didn't perform strongly in explaining why abusive supervision has a negative impact on employee well-being. This suggests that other factors (e.g., justice perceptions) may be stronger explanations.

**3. Long-term effects of retaliation.** The positive effect of retaliation on restored justice perceptions (and on well-being) was shown to persist over time. It also held when controlling for employees' baseline well-being and the alternate explanation of victim identity. In other words, engaging in retaliation against an abusive supervisor may have lasting benefits for employees.

**Practical Implications**

Our research suggests a practical way to counter the negative impact of abusive supervision on employee well-being: restoring a sense of justice.

*A Note Regarding Retaliation:*

-   Retaliation is just one of many possible responses to abusive supervision that can help restore a perception of justice. Other, more constructive, approaches could include expressive writing about experiences of injustice, a method also shown to help mitigate harm (Barclay & Skarlicki, 2009). Because retaliation has organizational costs and can contribute to a negative work environment, it's not something we endorse or recommend.

*What Can Organizations Do?*

-   The burden of responding constructively to abusive supervision isn't (and shouldn't be) necessarily all on the employees. Companies can (and should) step up and do their part too to ensure employees are not left to navigate these challenges on their own. That could mean devoting more effort towards identifying and addressing issues of fairness at work (e.g., a zero-tolerance policy against supervisory abuse, regular assessments, open communication channels, and leadership training). 
:::

------------------------------------------------------------------------

***Academic Publication***

### License to Retaliate: Good Deeds as a Moral License for Misdeeds in Reaction to Abusive Supervision

Why are "good soldiers" (employees known for their positive organizational contributions) most likely to become "bad apples" in the presence of abusive supervision?

Liang, L. H., **Coulombe, C.**, Skyvington, S., Brown, D. J., Ferris, D. L., & Lian, H. (2022). License to retaliate: Good deeds as a moral license for misdeeds in reaction to abusive supervision. *Human Performance, 35*(2), 94-112.

::: {.callout-caution collapse="true" appearance="minimal" icon="false"}
## What's the Gist?

Not all employees retaliate against abusive supervision. Some choose to "turn the other cheek" and not fight back when their bosses mistreat them, possibly because they feel it's morally wrong to act badly at work.

-   If people often help out and do things that would be considered morally good at work, they may be more likely to do something bad in return when their boss mistreats them.
-   This could be because they think their past good deeds make it okay to respond in a way that might not normally be considered right.
-   People who often ignore their moral rules may be even more likely to retaliate against abusive supervisors when they have a history of past moral behaviors at work.
:::

::: {.callout-note collapse="true" appearance="minimal" icon="false"}
## Read More

**\
Overview**

Research on abusive supervision reveals that despite the potential consequences, employees often engage in deviant behavior after being mistreated by their supervisors. This can include actions like intentionally lowering productivity and effort, stealing company property, ignoring instructions, and prolonging breaks. Surprisingly, though, it's often the exemplary employees – the "good apples" of the workplace – who show higher levels of deviance in these situations. But what drives this unexpected behavior? Why would those known for their positive conduct also be the most prone to veering off course? In this article, we delved into the realm of moral licensing theory to shed light on this phenomenon.

**What is Abusive Supervision?**

Due to its unfortunate prevalence in the workplace (with estimates suggesting that it affects more than 10% of employees; [Tepper et al., 2017](https://www.annualreviews.org/doi/abs/10.1146/annurev-orgpsych-041015-062539)), abusive supervision is a well-studied phenomenon in I/O Psychology. Characterized by behaviors like blame-shifting, invasions of privacy, and public humiliation, abusive supervision not only inflicts psychological distress on employees but also leads to negative organizational outcomes like decreased job performance and increased turnover intentions.

Interestingly, research suggests that victims of abusive supervision often take out their distress against the organization. One reason for this lies in the power dynamics between supervisors and their employees. Since supervisors wield control over valuable resources, direct retaliation against them is relatively riskier. Fear of hostility and further abuse may also lead employees to prefer to displace their frustration and anger toward the organization itself. That being said, not all employees react to this mistreatment in this way. Some choose to respond differently, perhaps turning the other cheek, ignoring the mistreatment, or focusing on mitigating its effects. So what factors influence which employees will retaliate against abusive supervision, and which will choose to endure it silently?

**What is Moral Licensing Theory?**

We turned to Moral Licensing Theory as a potential answer to this question. This theory posits that people want to balance their engagement in good and bad behavior to maintain a consistent moral equilibrium. Doing morally praiseworthy things, such as organizational citizenship behaviors (OCB) like staying at work after hours, checking in while on vacation, and volunteering for projects beyond formal job duties, can lead people to perceive that they've gained enough moral "capital" to justify their engagement in deviant acts as a form of retaliation. In other words, they might feel like because of their history of good behavior, they've acquired a moral license to behave badly in response to abusive supervision.

**Study 1**

In Study 1, we tested our first hypothesis that the amount of good behavior a worker shows (OCB) affects their tendency to act out against the organization when they experience abusive supervision. We predicted that when faced with abusive supervision, employees who'd shown a lot of good behavior would be more likely to act out against the organization compared to those who hadn't shown as much good behavior.

To test this, we surveyed over 190 full-time employees from a variety of industries and occupations. At Time 1, they were asked to complete an abusive supervision scale and to provide the contact information of their significant others (i.e., cohabitating partners). We then asked their significant others to rate how often the target participants tended to engage in OCBs. At Time 2, around two weeks later, we asked the target participants to rate how often they engaged in deviant organizational behaviors.

Overall, Study 1 provided support for our hypothesis. The **key findings** were as follows:

-   Individuals who experienced abusive supervision were more likely to engage in organizational deviance
-   This tendency was especially strong among those with a history of high levels of OCB, as rated by their significant others.
-   The results suggest that responses to abusive supervision may vary among people and may depend on their ability to morally justify their actions, influenced by their past moral behavior.

​**Study 2**

One key limitation of Study 1 was that we didn't directly test if there was an underlying moral explanation for the effect we saw. We accounted for this in Study 2 by testing if the effect was stronger among those with a high propensity to morally disengage. Our thinking here was that those who find it easier to turn off or ignore their moral compass (i.e., the internal rules that guide their behavior) might be especially likely to respond to abusive supervision with deviance when they've done a lot of OCBs.

We tested this idea by surveying over 200 full-time employees from different industries and roles. In an initial survey, we asked them to rate how often their supervisor engaged in a set of abusive behaviors. One week later, we measured their propensity to morally disengage. One week after that, we asked them to rate how often they engaged in OCB and organizational deviance.

The results of Study 2 were in line with what we were expecting. The **key finding** was as as follows:

-   Whether abusive supervision leads to bad behavior seems to depend on two things: how much employees help out at work and how likely they are to ignore their moral rules.
:::

------------------------------------------------------------------------

***Academic Publication***

### Third-Party Reactions to Supervisor Mistreatment Through an Identity Theory Lens

Does mistreatment by supervisors impact not only the targeted employees but also bystanders? Can social identity shed light on why employees react in certain ways to mistreatment based on their connection with their supervisors?

**Coulombe, C.**, Liang, L. H., & Brown, D. J. (2021). Third party reactions to supervisor mistreatment through an identity theory lens. *Canadian Psychology/Psychologie Canadienne, 62*(2), 195–203.

::: {.callout-caution collapse="true" appearance="minimal" icon="false"}
## What's the Gist?

Supervisory mistreatment in the workplace affects not only the victim but also bystanders who witness it.

-   Bystanders respond to mistreatment emotionally and behaviorally in various ways.
    -   Emotionally, some might feel anger towards the supervisor and empathy towards the victim, while others might feel contentment about the situation.
    -   Behaviourally, some might choose to help the victim and punish the supervisor, while others might choose to disparage the victim even more. 
-   Research suggests that these responses might be influenced by bystanders' motivation to see the world as a fair place, their sense of what is right and wrong, and a cost-benefit analysis of the pros and cons of helping the victim.
-   We argue that how much bystanders identify with their supervisor can also influence how they feel and behave.
    -   Those strongly identifying with the supervisor may justify mistreatment to protect their self-image.
-   Severe mistreatment, though, may challenge bystanders' identification and lead to feelings of discomfort.
    -   Depending on the emotion they feel as a result, they may be even more likely to punish the supervisor, help the victim, distance themselves from the supervisor, and/or reduce their identification.
:::

::: {.callout-note collapse="true" appearance="minimal" icon="false"}
## Read More

**Summary​**

Supervisory mistreatment in the workplace can have far-reaching implications, extending beyond the immediate victim to bystanders who witness this behavior. In the literature, bystanders have been found to respond in different ways when they see instances of abusive supervision. Emotionally, some have been found to experience anger towards the supervisor and empathy towards the victim, and others contentment or schadenfreude. Behaviorally, responses vary too, with some bystanders choosing to further marginalize or criticize the victim; others choosing to support the victim and seek retribution against the supervisor; and others choosing not to react at all.

In this theory paper, we explore different psychological theories to build a theoretical model aiming to help explain when and why a bystander may show each of these responses.

**Exploring Theories of Third-Party Reactions:**

We began by delving into the **belief in a just world theory**. This theory suggests that people, in general, are motivated to believe that the world is just and fair, where people get what they deserve and deserve what they get. It predicts that when bystanders observe supervisory mistreatment, they may assume that the victim deserved it and blame them as a way to uphold their belief in a fair and just world. While this theory helps explain some of the negative behavioral responses against victims of supervisory abuse, it does not necessarily explain why bystanders sometimes choose to respond in positive ways.

A theory that sheds light on these more positive responses is the **deontic justice theory.** This theory proposes that supervisory mistreatment violates people's sense of what is morally right and wrong and of how people should be treated in the workplace. When seeing someone being mistreated as such, bystanders may experience feelings of moral anger and feel compelled to retaliate against the supervisor to uphold principles of fairness and justice because they see it as the right thing to do.

So how do we explain bystanders' different reactions to supervisory mistreatment? A third theory, the **cost-benefit model of third-party reactions**, suggests that bystanders do a cost-benefit analysis of whether they should do something to help. They consider, for instance, if the supervisor could have acted better in the situation; if the person being mistreated did anything to cause it; and if things could have turned out better. If, through this analysis, they conclude that the situation is unfair, they'll then decide if helping is worth it. They might consider if it'll help make things better or worse, and if the potential good outcomes of helping outweigh the potential bad outcomes. This model is a little more nuanced, as it accounts for the possibility that the same bystander might not always respond in the same way when they witness supervisory mistreatment.

**Integrating Perspectives:**

While these theories explain why bystanders might react in different ways based on the factors involved in the situation they witness, they don't focus much on how the characteristics of bystanders themselves might affect their idea of fairness. This matters because everyone brings their own experiences and biases, which can change how they see things. What seems fair to one person might seem totally unfair to another, leading to different feelings and reactions.

In our model, we suggest that bringing a **social identity** perspective, considering how much a bystander identifies with their supervisor, can help us further understand why they react differently to supervisory mistreatment. Specifically, we propose that when someone sees their supervisor mistreating others, their sense of whether it's fair or not depends on how much they connect their identity with their supervisor.

In our model, we first propose that how much a bystander identifies with their supervisor will influence their evaluation of the fairness of the situation. Those who are not very highly identified with their supervisor may be more likely to perceive supervisory mistreatment as being unfair. In contrast, in situations where an employee strongly identifies with their supervisor, witnessing mistreatment by that supervisor towards another employee can be unsettling. It can make them feel like their view of their own identity is threatened because they're associated with someone who's behaving badly. To protect themselves, they might try to shift the blame away from the supervisor and criticize the victim instead. This might help them justify the mistreatment and protect their positive view of themselves. In other words, we think that how much an employee identifies with their supervisor can affect how they evaluate the mistreatment they see. The more employees identify with their supervisor, the less they'll be likely to see the mistreatment as unfair.

But what if the mistreatment is so bad that the bystander can't make excuses for it? Would bystanders who strongly identify with their supervisor feel even more discomfort when they see their supervisor, someone they feel a deep connection to, behaving unfairly? In our model, we propose that this may be the case.

Specifically, compared to a bystander who doesn't identify much with their supervisor, a bystander who highly identifies may be more likely to see the mistreatment as unfair when they can't rationalize it away, and to feel discomfort about their connection with their supervisor. This discomfort may result in different emotions, which then influence how they'll behave. Drawing on the literature on moral emotions, we argue that:

-   The bystander might feel angrier towards the situation and toward the supervisor. In this case, they might feel more driven to help the victim and punish the supervisor.
-   The bystander could also feel guiltier by association, in which case they might feel a greater need to try to make things right by helping the victim or speaking up about the mistreatment.
-   Finally, the bystander could also feel more shame. If this is the case, they may be more likely to want to distance themselves from the supervisor and reduce how much they identify with them. This could lead them to reduce their contact with their supervisor and how much they see them as an important part of their identity.

Overall, by integrating identity theory in the literature on third-party reactions to supervisory mistreatment, our model synthesizes the deontic justice model with the belief in a just world theory. Similar to individuals with strong just-world beliefs who tend to blame victims, we propose that third parties who strongly identify with the supervisor may also blame and derogate the victim, affecting their perceptions of fairness. Our model also suggests those experiencing a relational identity threat when they see unjust mistreatment from someone they identify with may be more likely to feel moral anger and be motivated to punish the wrongdoer and help the victim.
:::

------------------------------------------------------------------------

***Conference Poster***

### Investigating the "We" in Me: Within-Person Fluctuations in Organizational Identification

Does employees' attachment to their organization vary over time? What are the day-to-day factors that might influence this variation? What are the outcomes of these variations on employees' performance and turnover intentions?

[View the Poster](files/claudie_coulombe_organizational_identification_poster.pdf)

**Coulombe, C.** & Spence J. *Investigating the “we” in me: Within-person fluctuations in organizational identification.* \[Poster\]. Canadian Psychological Association 2022 Annual National Convention, Calgary, Canada.

::: {.callout-caution collapse="true" appearance="minimal" icon="false"}
## What's the Gist?

-   People spend a lot of their time working. Some have estimated that the average person will spend around 90,000 hours of their lifetime at work. That’s 3750 days – and, for some, this number might be even higher than that.
-   It may not come as a surprise, then, that organizational psychology researchers have found that it’s not uncommon for us to see our work as an important part of who we are. Related to this notion is the idea of organizational identification (OID).
    -   OID is a component of organizational attachment that reflects the degree to which someone views their membership to an organization as self-defining. It reflects how much they see their organizational membership as an important part of who they are.
-   Over the past 30 years, organizational researchers interested in this construct have spent a lot of time and effort identifying potential antecedents and outcomes of OID. Interestingly, this research has mostly treated OID as a stable, trait-like construct, assuming that people will be constant in their OID over time.
-   Some theorists, though, have suggested that OID might be more dynamic than traditionally thought, including in the short term, and that people might not just vary from each other in their OID, but they could also vary from themselves in their level of it over the course of their day to day organizational life.
-   With this research project, I helped shed more light on this question by looking at whether employees fluctuate in their daily level of OID, and testing potential predictors and outcomes of these fluctuations.
-   Specifically, I conducted an experience-sampling daily diary study with over 100 full-time employees to test if fluctuations occur in daily OID and, if so, whether these fluctuations result from daily changes in the satisfaction of OID motives (needs that motivate people to identify with an organization) and influence daily job performance and turnover intentions.
-   Overall, this study constitutes a promising first step towards better understanding the stability or changeability of OID in everyday organizational life and the factors that may affect employees’ attachment (and, subsequently, their turnover intentions and job performance) over time.
:::

::: {.callout-note collapse="true" appearance="minimal" icon="false"}
## Scientific Abstract

Workplaces are becoming more flexible, virtual, and dynamic. Concerns that these changes may affect levels of organizational attachment have provoked interest in better understanding what shapes the formation and maintenance of these bonds. Increased attention has been paid to organizational identification (OID), reflecting the degree to which employees view their organizational membership as self-defining. To date, research has examined between-person predictors and outcomes of OID, but we still know little about how it unfolds within-person as employees experience various situations and changes at work. To better understand these dynamics, an experience-sampling study examining within-person predictors and outcomes of OID was conducted. This study tested if fluctuations occur in daily OID and, if so, whether these fluctuations result from daily changes in the satisfaction of OID motives and influence daily job performance and turnover intentions. Over 100 employees completed three daily surveys for two consecutive workweeks. Measures were separated in time, and multilevel analyses will be conducted to account for the nested data structure. Overall, this study constitutes a promising first step towards better understanding the stability or changeability of OID in everyday organizational life and the factors that may affect employees’ attachment over time.
:::

------------------------------------------------------------------------

***Conference Poster***

### Introducing Humility in Leadership: Identifying Humble Leadership Passages for Leader Prototype Interventions

Why do we tend to associate dominance and assertiveness with good leadership? Does this make it hard for us to notice the power of humility? Can we develop interventions to include more humility in people's ideas of what makes a good leader?

[View the Poster](files/claudie_coulombe_leadership_humility_poster.pdf)

**Coulombe, C.,** Liang, L. H., Brown, D. J., & Brunner, L. (2020, May). *Introducing humility in leadership: Identifying humble leadership passages for leader prototype interventions.* \[Poster\] Canadian Psychological Association Annual Meeting, Montreal, QC, Canada.

**\*Third place winner of Canadian Society for Industrial Organizational Psychology Best Student Poster Award**

::: {.callout-caution collapse="true" appearance="minimal" icon="false"}
## What's the Gist?

In today's society, we often see leaders as strong, confident individuals who take charge. Traits like humility, which involve being self-aware, appreciative of others, and open to learning, aren't typically seen as essential leadership qualities.

-   But research suggests that leaders who show humility actually benefit their employees and organizations. So, we're exploring ways to promote humility as an important trait for leaders.
-   The goal of our research was to create materials that could be used to develop interventions meant to make humility a bigger part of what people tend to consider when they think of what makes a good leader.
-   In our research project, we selected passages from ancient Chinese texts that specifically talked about humble leadership. Through three studies, we used statistical techniques to validate them, to ensure that they specifically reflected humility rather than related constructs. Overall, we ended up with 8 passages that were clear and that fit the common definition of humility in the literature.
-   Future research will involve designing reading-writing interventions using these passages, to see if reading about humble leadership can help increase the importance they give to it when they think of what makes a good leader.
-   Overall, this research is just the beginning of trying to encourage more humility in our idea of leadership, which could have positive effects on workplaces and organizations.
:::

::: {.callout-note collapse="true" appearance="minimal" icon="false"}
## Scientific Abstract

The tendency of Western society to value agency over communion appears to extend to perceptions of leadership. When identifying prototypic traits characterizing a leader, attributes such as dominance, assertiveness, and competence come readily to mind, while characteristics of humility (i.e., self-awareness, appreciation of follower strengths, willingness to learn) are less accessible. Nonetheless, research has documented the benefits of leader humility on employee and organizational outcomes. As such, interventions designed to include more humility in leader prototypes may prove beneficial. Through two studies, we integrate implicit leadership theory with expressive writing research to generate and test material useful for future leader humility interventions. In Study 1a (N=219), a graduate student knowledgeable in the concept of humility selected 30 passages from “The Governing Principles of Ancient China.” We validated them using a Q-Sort methodology, identifying 20 passages as specifically reflecting a definition of humility rather than related constructs (i.e., modesty, openness to experience, learning orientation, anti-narcissism, low self-esteem, and core self-evaluations). In Study 1b (N=186), we further validated these 20 passages, retaining 8 based on clarity criteria. Study 2 will be conducted in December 2019. Participants will be randomly assigned to read 1 of the 8 humble leadership passages, and asked to reflect on and write about the beneficial traits associated with the leadership style depicted. Through Network Analysis, we will identify passages increasing the centrality of humility in participants’ leader prototype. Together, these studies will constitute a promising first step in investigating interventions aimed to integrate more humility in leader prototypes.
:::
